### ISSUE TITLE
Doesn't build to correct filepath

### ISSUE THREAD

**Issue by gpoitch** [ebryn/ember-cli-cssnext#2]
This builds to app.css, where ember-cli defaults to [app-name].css.
It also should read from the outputPaths options for alternate directory/filenames and multiple output files.

**Comment by bcardarella** [comment]
I've discovered the source of this: https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/master/preprocessors.js#L131-L152

For some reason when ember-cli's css preprocessor plugin count is greater than 0 it doesn't rewrite the output location to `<appname>.css`

I guess the argument is that the plugins themselves should dictate the final location of the files? Seems odd to me. `broccoli-funnel` is being useed, which just makes an assumption of the output directory based upon the input directory. Normally this would be OK as it outputs to `app.css`, I would expect ember-cli's final preprocessor to handle the file name change but as indicated above this is being skipped. In this case `ember-cli-cssnext` needs to override the `getDestinationPath` function.

@stefanpenner @rwjblue - is this the intent of that conditional? Any more background here? It seems like additional unnecessary overhead for each css ember-cli pre-processor to have to account for the final build location of the CSS files.

In the mean time I'm going to submit a PR to fix this issue. I do believe though that it shouldn't be the responsibility of this plugin to determine the final destination of its output file, that should be handled upstream in ember-cli itself.

**Comment by gpoitch** [comment]
@bcardarella I have a fork https://github.com/gdub22/ember-cli-cssnext which is essentially a rewrite.  It solves this using ember-cli's outputPaths option and also fixes a handful of other gotchas.

**Comment by bcardarella** [comment]
@gdub22 turns out your fork might be better, as this version doesn't support `@import` because of `broccoli-cssnext`.
